#!/command/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

#readarray -td, PORTS <<< "${WEBUI_PORTS}"
#sed -i "s/0.0.0.0:5000/0.0.0.0:${PORTS[2]%%/*}/" "${APP_DIR}/nginx.conf"

body_size=$(grep 'network.xmlrpc.size_limit.set.*' "${CONFIG_DIR}/rtorrent.rc" | awk -F '=' '{print $2}' | xargs)
sed -i "s/@XMLRPC_SIZE_LIMIT@/${body_size,,}/" "${APP_DIR}/nginx.conf"

exec s6-setuidgid hotio nginx -c "${APP_DIR}/nginx.conf" -p "${CONFIG_DIR}/rpc2" -e "error.log" -g "daemon off;pid nginx.pid;"
