#!/command/with-contenv bash
# shellcheck shell=bash

# shellcheck source=/dev/null
source /etc/s6-overlay/scripts/bash-functions

set -e

umask "${UMASK}"

echo "
----------------------------------------------------------------------
ENVIRONMENT APP
----------------------------------------------------------------------
WEBUI_PORTS=${WEBUI_PORTS}
FLOOD_AUTH=${FLOOD_AUTH}
----------------------------------------------------------------------
"

if [[ ! -f "${CONFIG_DIR}/rtorrent.rc" ]]; then
    log_inf "Installing default [${CONFIG_DIR}/rtorrent.rc] file."
    cp "${APP_DIR}/rtorrent.rc" "${CONFIG_DIR}/rtorrent.rc"
    find "${CONFIG_DIR}/rtorrent.rc" -maxdepth 0 \( ! -user hotio -or ! -group hotio \) -exec chown hotio:hotio {} +
fi

if [[ ! -f "${CONFIG_DIR}/rpc2/basic_auth_credentials" ]]; then
    log_inf "Creating new [${CONFIG_DIR}/rpc2/basic_auth_credentials] file for RPC2."
    [[ ! -d "${CONFIG_DIR}/rpc2" ]] && mkdir "${CONFIG_DIR}/rpc2"
    rpc2_password=$(openssl rand -base64 10)
    echo "hotio:$(openssl passwd -5 "${rpc2_password}")" >> "${CONFIG_DIR}/rpc2/basic_auth_credentials"
    log_inf "Your RPC2 credentials are [hotio:${rpc2_password}]."
    find "${CONFIG_DIR}/rpc2" \( ! -user hotio -or ! -group hotio \) -exec chown hotio:hotio {} +
fi
