#!/command/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

echo "
----------------------------------------------------------------------
ENVIRONMENT APP
----------------------------------------------------------------------
WEBUI_PORTS=${WEBUI_PORTS}
FLOOD_AUTH=${FLOOD_AUTH}
----------------------------------------------------------------------
"

if [[ ! -f "${CONFIG_DIR}/rtorrent.rc" ]]; then
    echo "Installing default \"rtorrent.rc\"..."
    cp "${APP_DIR}/rtorrent.rc" "${CONFIG_DIR}/rtorrent.rc"
    chown hotio:hotio "${CONFIG_DIR}/rtorrent.rc"
fi

find "${CONFIG_DIR}" -name rtorrent.lock -type f -delete
