#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

if [[ ${FLOOD_AUTH} == true ]]; then
    FLOOD_OPTION_AUTH=default && export FLOOD_OPTION_AUTH
    echo "rTorrent socket file is \"/dev/shm/rtorrent.sock\"."
else
    FLOOD_OPTION_AUTH=none && export FLOOD_OPTION_AUTH
fi

exec s6-setuidgid hotio "${APP_DIR}/flood" --rundir "${CONFIG_DIR}/flood" --host 0.0.0.0 --port 3000 --rtsocket "/dev/shm/rtorrent.sock" --baseuri "${FLOOD_BASEURI}"
