#!/usr/bin/with-contenv bash
# shellcheck shell=bash

umask "${UMASK}"

if [[ ! -f "${CONFIG_DIR}/rtorrent.rc" ]]; then
    echo "Installing default \"rtorrent.rc\"..."
    cp "${APP_DIR}/rtorrent.rc" "${CONFIG_DIR}/rtorrent.rc"
    chown hotio:hotio "${CONFIG_DIR}/rtorrent.rc"
fi

find "${CONFIG_DIR}" -name rtorrent.lock -type f -delete
